language: php
sudo: false
dist: trusty
php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - master
    - nightly
matrix:
    fast_finish: true
    allow_failures:
        - php: master
        - php: nightly
os:
    - windows
    - linux
script:
    - composer validate
    - composer update
cache:
    directories:
        - vendor
        - $HOME/.cache/composer
